### ISSUE TITLE
sendForcePacket crash fabric 1.19.2

### ISSUE THREAD

**Issue by snatella** [kyrptonaught/CustomPortalApi-Polymer#1]
Hello again Kyrptonaught, sorry I'm here to be a pain again

On portal ignition using cpa-polymer to alleviate the need for everyone to have datapackportals, the initial ignition of a portal causes a hard server crash (does save though).

The portal itself does appear to light and generate the shimmer just before the crash.

Using
- cpa-polymer-1.0.0-1.19
- datapackportals-1.2.1-1.19

This crash with cpa-polymer happens with or without customportalapi-0.0.1-beta57-1.19

```
[14:02:48] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.kyrptonaught.customportalapi.networking.ForcePlacePortalPacket.sendForcePacket(net.minecraft.class_3222, net.minecraft.class_2338)'
        at net.kyrptonaught.customportalapi.CustomPortalBlock.onPolymerBlockSend(CustomPortalBlock.java:538) ~[customportalapi-0.0.1-beta57-1.19.jar:?]
        at eu.pb4.polymer.impl.networking.BlockPacketUtil$SendSingleBlockInfo.run(BlockPacketUtil.java:62) ~[polymer-0.2.18+1.19.2-cd67caaa292fd17e.jar:?]
        at net.minecraft.class_3244.handler$bcl000$polymer_sendSequencePackets(class_3244.java:5662) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:260) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

On server (re)start, the portal is still lit and the portal works fine.

**Comment by kyrptonaught** [comment]
Cpa-polymer needs to be updated to work with newer versions of cpa. I did this previously, let me find the jar

**Comment by kyrptonaught** [comment]
1.0.2 was released which should fix this

**Comment by snatella** [comment]
Yup this nails it, thanks!
